#!/bin/bash
# ------------------------------------------------------------------
# [Author: Boyan Naydenov] TGS Control Suite
#  Terrassa Ground Station (UPC - ESEIAAT) script designed to handle
#  the different functional blocks (antenna controllers, radio, webcam).
# ------------------------------------------------------------------

# for file  to work globally: sudo ln -s /path/to/file /usr/bin/start-tracking

echo "Starting PA, LNA and LED \n"
stty -F /dev/ttyACM0 cs8 9600 ignbrk -brkint -icrnl -imaxbel -opost -onlcr -isig -icanon -iexten -echo -echoe -echok -echoctl -echoke noflsh -ixon -crtscts
sleep 1
tmux new-session -s track -d 'echo "start" > /dev/ttyACM0'
sleep 1

echo "Starting GS232B communication \n"
tmux split-window -v 'suitetgs -r'
sleep 1

echo "Starting rotator calibrator \n"
tmux split-window -h 'suitetgs -i'
sleep 1
echo "Starting Gpredict and engage in tracking \n"
tmux select-pane -U
tmux split-window -h 'suitetgs -g'
tmux attach -t track